version: "2"
services:

  shard1n1:
    container_name: shard1n1
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet shard1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/shard1n1:/data/db

  shard1n2:
    container_name: shard1n2
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet shard1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/shard1n2:/data/db

  shard1n3:
    container_name: shard1n3
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet shard1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/shard1n3:/data/db

  mconfig1:
    container_name: mconfig1
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/mconfig1:/data/db

  mconfig2:
    container_name: mconfig2
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/mconfig2:/data/db

  mconfig3:
    container_name: mconfig3
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/mconfig3:/data/db

  mongos1:
    container_name: mongos1
    image: mongo:3.0.14
    depends_on:
      - mconfig1
      - mconfig2
      - mconfig3
    command: mongos --configdb mconfig1:27017,mconfig2:27017,mconfig3:27017 --port 27017
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro

  mongos2:
    container_name: mongos2
    image: mongo:3.0.14
    depends_on:
      - mconfig1
      - mconfig2
      - mconfig3
    command: mongos --configdb mconfig1:27017,mconfig2:27017,mconfig3:27017 --port 27017
    ports:
      - 27018:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro